AllCops:
  TargetRubyVersion: 2.3

# I prefer no empty line between magic comment and requires.
Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# I prefer to put two spaces before inline comment, Rubocop does not allow to
# set exception for this.
Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  CountKeywordArgs: false

# I know where to (not) use "and" / "or".
Style/AndOr:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/FileName:
  Exclude:
    - 'lib/yaml-env-tag.rb'

# I don't use guard clause when line would be too long.
Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile*
    - Rakefile
    - '*.gemspec'

Style/NegatedIf:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
