dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - jruby-9.1.12.0
env:
  global:
    secure: "dl/cnksKlFWBNLaQSO3MvbdkQFHwEUidN4C+REXoCzjejdAkkXSoyiNQg9s6oj/IThVv1Eo8TJW97W1xvhv8E+tEP36DNP8ZzfwcNsYk/bipnrlP8uBNeg01A0G0LRvBu0UjnbN1dgyePcNfSmhxUbJUp3+1QjS+uxQ3pzucr/gFzhKoL7wYlp2ukdBmdLwKrvhLHnu74EV7dmOUXc0cbFsgl0K5VNGr9mml+DvGHQ7WX9Vv6JRBvigA3GwysNp88RUkRWd0NLw39LaGVrNEqB8Y+NrbBdtl5Ri77jC4o0Eea1EB7UXIya5TV/giozFKtej8IgVPmAARYt06Ld6xFIoWXML9SuiP6ReEg9Kap+EqJffhf6973HEwIsT85hNfFTyyEtEPigP6pIDOFePRFEOcVp4WNVbIyIf7Pji3ub+uvHQ8qPTqhjs91UOmG5zFLKJ9DWWZ4n/j0mEKqYKt0R1gOhU8BVlDf1srFwnDYorfbEYKuaoEKS/LyUyZLheUq6NfJujkIeZJeDmwTiWA9DUHpbJ8MuqvjW02Ezr+cOPwbWPyCmcW5wQbJkdGexL5ZVTDKaAZYqQ/Xpk+lHnVnmR04Hj84m0dNxH8OgdVj+1eA6AKFEvWVUzoAFt3h1DpdZqoVj7ajxmJVHZea3etcPd6TESiVDofm/sW2nQ7ODU="  # CODACY_PROJECT_TOKEN
script:
  - bundle exec rake spec
  - bundle exec rake rubocop
deploy:
  provider: rubygems
  api_key:
    secure: "N9KMWxtaUN1PoEsEPYgCRTaVzV6EKXjhs9KySNNVqqOTF45FXBToaGoZYuc3e7AA0bnAYbBHMPT8ExeY+JHLDFyGwbS6xer9ac9PLacuLPTJwg1ZoXMgfsn9S9D7pTuGDCIfwxoM+r0bKrMtRWqUS0s5Af7NiIONGFbQvC0l92S+MQAigfdh8T+3nOYWHxLBZzrz9R2jqFd3nfk4LXv8svkjbSs0iFsd4r8QqSxj6bnKjQ0yGWHTzEroVwe5byUVEexJJPqZ5kXTJDFQ07lVWbLf6PNUkAw11PEhtCt41lwunAyhlbVnPP6Ib6C1vPehl7t3ovEnVc9isnzPrNYBDSMfgg3kFmMXuNSXpa5zUfpEhQJ17cyqF/a2JH1uFaRLWVdUp8K2PKC9WLbH7MO0AwS30SW3TfiVF6djFALZHw93I09p5K8q2pfkZRixB3qAQapsFDwldo/dci2Ukq+Ls1zbj8MMow0grLZdZHsZYeJFdoEcy+LrhkSILk1lC/bSuTpRqGhMYlR+jH77EmX5c7gTibuqNOMhek2yeA3a9a6FcUQQB5V0noWwgc074jUcEvd6aRzb48zLAezNgKfspw+9RYPxOZ4pFyxgmlrRcpiU/8HW84C/IhbDhlGuFCIo8ltqqdxxSkKcg9f8ANhT+mmPF9yzMwltxi6A0I3toM4="
  on:
    tags: true
    condition: ${TRAVIS_JOB_NUMBER#*.} = 1
