= YAML !ENV tag
Jakub Jirutka <https://github.com/jirutka>
// custom
:gem-name: yaml-env-tag
:gh-name: jirutka/{gem-name}
:gh-branch: master
:codacy-id: d1b32c16409c46a0b81882a679713a67

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}[Build Status, link="https://travis-ci.org/{gh-name}"]
image:https://api.codacy.com/project/badge/Coverage/{codacy-id}["Test Coverage", link="https://www.codacy.com/app/{gh-name}"]
image:https://api.codacy.com/project/badge/Grade/{codacy-id}["Codacy Code quality", link="https://www.codacy.com/app/{gh-name}"]
image:https://img.shields.io/gem/v/{gem-name}.svg?style=flat[Gem Version, link="https://rubygems.org/gems/{gem-name}"]
endif::env-github[]

A custom YAML tag for referring environment variables in YAML files.
No need to use ERB in YAML just to set some keys from environment variables.

[source, yaml]
.*Sample YAML file using ENV! tag*
oauth:
  client_id: ENV! API_CLIENT_ID
  client_secret: ENV! API_CLIENT_SECRET


== Usage

Just require `{gem-name}` and load YAML as you’re used to:

[source, rb, subs="+attributes"]
----
require '{gem-name}'

yaml = YAML.load('secret: ENV! API_CLIENT_SECRET')
yaml['secret']  # => "top-secret"
----

However, if you use `YAML.safe_load` (which is highly recommended), you need to explicitly whitelist `YamlEnvTag::EnvVariable`:

[source, rb]
YAML.safe_load(..., [YamlEnvTag::EnvVariable])

If the specified environment variable does not exist (i.e. is not set), `YAML` will raise exception `YamlEnvTag::MissingEnvVariableError` when loading the file.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
